version: '3'

services:

  redis:
    image: "redis:alpine"
    container_name: demo_redis
    networks: [main]
    ports:
      - "6379:6379"

  amqp:
    image: "rabbitmq:3"
    container_name: demo_amqp
    networks: [main]
    ports:
      - "5672:5672"
      - "15672:15672"

  server:
    build: .
    ports:
      - "8000:8000"
    networks: [main]
    command: ["sh", "/wait-and-run.sh", "/server-entrypoint.sh"]
    env_file: .env

  command-consumer:
    build: .
    networks: [main]
    command: ["sh", "/wait-and-run.sh", "/command-consumer-entrypoint.sh"]
    env_file: .env

networks:
  main:
