parameters:
    kernel.secret: yoursecretshouldbehere
    app.path: '../..'

framework:
    form: false
    assets: false
    session: false
    translator: false
    php_errors:
        log: false


#
# AMQP Bundle configuration
#
amqp:
    clients:
        main:
            host: "%env(AMQP_HOST)%"
            port: 5672
            vhost: /
            user: guest
            password: guest


#
# Redis Bundle configuration
#
redis:
    clients:
        main:
            host: "%env(REDIS_HOST)%"


#
# Command Bus Bundle configuration
#
command_bus:
    command_bus:
        async_adapter:
            adapter: amqp
            amqp:
                client: main
                queue: "%env(AMQP_COMMANDS_QUEUE)%"

event_bus:
    exchanges:
        events: "%env(AMQP_EVENTS_EXCHANGE)%"
    async_adapter:
        adapter: amqp
        pass_through: false
        amqp:
            client: main


#
# Preload Bundle configuration
#
preload:
    services:
        "Domain\\ValueRepository": ~
        "App\\Controller\\ViewValuesController": ~
    presets:
        - "@symfony"
        - "@drift"
        - "@react"
        - "Drift\\Twig\\Preset\\TwigPreset"
        - "Drift\\Redis\\Preset\\RedisPreset"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: "%app.path%/src/Controller"
        tags: ['controller.service_arguments']


    # Query and Command handlers are autowired under the Domain namespace. With
    # these simple tags, we are defining that all classes found there are
    # defined as handlers, taking the default method class parameter as usable
    # class to handle
    Domain\QueryHandler\:
        resource: "%app.path%/src/Domain/QueryHandler"
        tags: ['query_handler']

    Domain\CommandHandler\:
        resource: "%app.path%/src/Domain/CommandHandler"
        tags: ['command_handler']

    Domain\EventListener\:
        resource: "%app.path%/src/Domain/EventListener"


    # Infrastructure classes are defined under \Infrastructure namespace. You
    # can find the alias in composer.json under the PSR-4 section. Autowiring is
    # used here to create all services, and final alias is generated after all.
    # Feel free to comment the unused adapter for performance increasing.
    Infrastructure\Redis\:
        resource: "%app.path%/src/Redis"
        tags:
            - {name: preload, method: loadAll}

    Domain\ValueRepository:
        alias: Infrastructure\Redis\RedisValueRepository